### ISSUE TITLE
Regarding the puppy raffle [H-4] bug found where `Malicious winner can forever halt the raffle` But this is not actually true

### ISSUE THREAD

**Issue by saikumar279** [Cyfrin/4-puppy-raffle-audit#18]
Here like i was able to write a test case where even after reverting we can call selectwinnner which would choose the winner.

Below is the test case and attacker contract:

**Attacker contract:**

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.7.6;

import {PuppyRaffle} from "../src/PuppyRaffle.sol";

contract Attacker {
    fallback() external payable {
        revert();
    }
}

```

**Test for the same:**

```javascript
function testRevert() public {
        uint256 playerNum = 5;
        address[] memory playersSecond = new address[](playerNum);
        for (uint256 i = 0; i < playerNum; i++) {
            Attacker attackerAddress = new Attacker();
            playersSecond[i] = address(attackerAddress);
        }
        address[] memory playersThird = new address[](1);
        puppyRaffle.enterRaffle{value: entranceFee * playerNum}(playersSecond);
        puppyRaffle.enterRaffle{value: entranceFee}(playersThird);
        vm.warp(block.timestamp + duration + 1);
        console.log(puppyRaffle.totalFees());
        try puppyRaffle.selectWinner() {} catch {
            console.log(puppyRaffle.totalFees());
            uint256 playerNumSecond = 90;
            address[] memory playersSecondThird = new address[](
                playerNumSecond
            );
            for (uint256 i = 0; i < playerNumSecond; i++) {
                playersSecondThird[i] = address(uint160(i) + 200);
            }
            puppyRaffle.enterRaffle{value: entranceFee * playerNumSecond}(
                playersSecondThird
            );
            puppyRaffle.selectWinner();
            console.log(puppyRaffle.totalFees());
        }
    }
```

**Comment by EngrPips** [comment]
Hello, @saikumar279, Thanks for this brilliant catch. You are correct that there are chances that the lottery funds could be distributed after an initial revert from the `selectWinner` function of the contract. An increment in the length of the player's array will definitely cause the `selected winner` from the array to change, but nevertheless, there is still a possibility of the contract choosing the `malicious` winner over and over again. For this reason, the finding can be degraded to Medium instead of High. @PatrickAlphaC, I look forward to hearing what you say on this, sir.

**Comment by saikumar279** [comment]
Hey @EngrPips 

There is no need for player to enter the raffle even after revert.
Because due to change in block.difficulty,block.timestamp and msg.sender there can be new random number generated when we call selectwinner again which may not be index of the contract address right?

Am i correct or anything wrong in the way iam thinking?

**Comment by EngrPips** [comment]
Yeah, You are thinking right. There are too many variables that are bound to change from time to time, which will easily make the selected winner change. Let's look forward to what @PatrickAlphaC  will say to this.

**Comment by PatrickAlphaC** [comment]
gm! Good shout! You're right that you can work around this, but it requires, as you've seen, multiple new entries or multiple new attempts to end the raffle. Let's say a hacker entered the raffle 1,000 times, due to one of the previous bugs, it's really hard to enter the raffle more due to how expensive it becomes to enter the raffle. Now, the hacker has most of the slots, and some would basically have to keep entering and keep rerolling to try to start a new raffle! 

Not sure I explained that correctly, but essentially this is still a bug because the raffle becomes borderline impossible to restart without others wasting a lot of money (like entering the raffle). If users lose funds, that's typically high impact!

**Comment by saikumar279** [comment]
Hey @PatrickAlphaC 
Thanks for clarification! I now see how this issue could significantly impact users, especially with the difficulty of restarting the raffle and the potential for others to waste funds. Thanks for helping  understand the implications better.
